### ISSUE TITLE
Is this an Eleuther project?

### ISSUE THREAD

**Issue by afiaka87** [cfoster0/CLAP#23]
Title

**Comment by cfoster0** [comment]
Yesn't. Definitely Eleuther-affiliated, but I dunno if it rises to the level of "an Eleuther project" yet.

**Comment by cfoster0** [comment]
What's GCE?

**Comment by cfoster0** [comment]
If you're referring to Google Compute Engine, I don't think the code is or should be specific to it. Assuming there's capacity within our TRC quota, sure, we can train on them. Otherwise, we should hopefully be able to use the other (non-Google GPUs) Eleuther has access to.

**Comment by afiaka87** [comment]
> If you're referring to Google Compute Engine, I don't think the code is or should be specific to it. Assuming there's capacity within our TRC quota, sure, we can train on them. Otherwise, we should hopefully be able to use the other (non-Google GPUs) Eleuther has access to.

**Comment by afiaka87** [comment]
> If you're referring to Google Compute Engine, I don't think the code is or should be specific to it. Assuming there's capacity within our TRC quota, sure, we can train on them. Otherwise, we should hopefully be able to use the other (non-Google GPUs) Eleuther has access to.

Yes - I was referring to GCE. I updated my comment with more context.
