### ISSUE TITLE
Set Up Package and Directory Structure

### ISSUE THREAD

**Issue by cfoster0** [cfoster0/CLAP#9]
Would be great if this was set up with the basics of a Python package and any conveniences that make sense. Since there are a couple of different subcomponents in this project, we probably also want to figure out a directory structure so that people working on different aspects aren't stepping on toes.

**Comment by louisgv** [comment]
Also would be cool to have a collab notebook on here so folk can plug-n-play.

**Comment by cfoster0** [comment]
Agreed! Once we have models to play with, it would be nice to give a quick example of how to embed audio and/or text with it

**Comment by louisgv** [comment]
Are we thinking monorepo or are we looking at mimicking one of the project out there?

**Comment by cfoster0** [comment]
For now, let's do a monorepo. We can think about splitting out inference code once we cross that bridge.

**Comment by cfoster0** [comment]
This was partially addressed in #11. Still need to settle on a structure for any non-model code we might want to include.

**Comment by cfoster0** [comment]
Closing for now.
